# Site settings
title: Welcome to the Tweaker Zone 
email: aniket.lamba@gmail.com
url: https://mr-tweaker.github.io
description: "Custom ROMs,social media links and a random description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: mr-tweaker

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/u_remedy
  - title: facebook
    url: https://facebook.com/aniket.lamba111
  - title: xda 
    url: http://forum.xda-developers.com/member.php?u=4743557
  - title: google plus
    url: https://plus.google.com/+AniketLamba
  - title: github
    url: https://github.com/mr-tweaker
  - title: instagram
    url: https://www.instagram.com/undesirable_remedy

# Build settings
markdown: kramdown
permalink: pretty
